## Part II: Practice Scripts

#### Add your scripts from this section as separate documents into your github repository. Below each question write the name of the script so I can find them. All scripts should be documented with in-line documentation.

#### Q.1. Create a documented python script that would

a. take this number 112345678911234566 and count the number of 2s in the string and print out the number.

b. take a sentence from user input, turn it all to lowercase letters and remove the spaces and count the length and print out the length. You choose the sentence.

In [2]:
#Python script to count number of 2s in a given string

I= ('112345678911234566') #enter the number as a string
print (list(I)) #list each character in a string
count=0
for num in list(I): #use for loop control flow statement 
    if num=='2':    #use if else statement to count the number only when the value is 2
        count=count+1  #count the number is the value matches
    else:               
        pass           #else pass the character in the string
print('number of 2s is', count,'.') #print out the number of 2s in the given string

['1', '1', '2', '3', '4', '5', '6', '7', '8', '9', '1', '1', '2', '3', '4', '5', '6', '6']
number of 2s is 2 .

In [25]:
#Python script to input a sentence, change it to lower case sentence, and count the length without spaces

A = input ("Input your sentence here:") #input any sentence you like
B = A.lower()                          #changes it to lowercase sentence
C = (B.replace(' ',''))                #removes the spaces in between the words to change it to letters
print("Your lowercase letters are:",C,".") #print your lowercase letters
Count_length = len(C)                   #count the length of your letters
print ("Length of your sentence without spaces is",Count_length,".") #print the length of your letters

Input your sentence here:My name is PB.
Your lowercase letters are: mynameispb. .
Length of your sentence without spaces is 11 .

#### Q.2.Create a documented python script that will do the following two things. For each task, first write the pseudocode, comment out the pseudocode and beneath the pseudocode write the script.

a.Create a list of numbers (any numbers you like). Then loop through the items in the list adding 1 to every number and print those numbers.

b.Create a dictionary of animals and their sizes (make up whatever you want). Print out the keys of the dictionary. Make a list of all the animals and then write an if else statement to print out the animal name and the word “big” if the weight is over 20 grams and the word “small” if the weight is less than 20 grams.

# a. Pseudocode
#### 1. Create a list of numbers of our choice  
#####use random numbers to make a list i.e. List_num = [0, 1, 2, 3, 4, 5, 6]
#### 2.  Make a new list adding +1 in each of our original number 
#####use for to loop through the list, new_list = [x+1 for x in List_num]
#### 3. Print the new list

In [51]:
List_num = [0,1,2,3,4,5,6]
new_list = [x+1 for x in List_num]
print(new_list)

[1, 2, 3, 4, 5, 6, 7]

In [70]:
#Alternative method 1

list = [0,1,2,3,4,5,6] 
for i in range(len(list)):     #range will give (0, 6) i.e. 0,1,2,3,4,5
      list[i] = list[i] +1
print(list)

[1, 2, 3, 4, 5, 6, 7]

In [107]:
list = [0,1,2,3,4,5]
range(len(list))

range(0, 6)

# b. Pseudocode

#### 1. Create a dictionary with key as animal name/species and value as it's weight 
#####animal_dictionary= {'monkey':15,'zebra':25,'donkey':20,'cat':10,'dog':16,'tiger':30,'elephant':100,'wolf':25} 
 
#### 2. Take out the keys only to get the list of animals 
#####print(animal_dictionary.keys())
#### 3. Do a loop on dictionary for animal, weight in (animal_dictionary.key( )) 

#### 4. Print key which is animal name
#####print ('Animal is: ', animal) 
#### 5. If weight > 20, print 'big' for that animal and if weight < 20, print 'small' for that animal 
#####if weight>20:
        print('big')
    else:
        print('small')

In [34]:
animal_dictionary= {'monkey':15,'zebra':25,'donkey':20,'cat':10,'dog':16,'tiger':30,'elephant':100,'wolf':25} 
print(animal_dictionary.keys())
for animal, weight in animal_dictionary.items():
    print('Animal is:',animal) 
    if weight>20:
        print('big')
    else:
        print('small')

dict_keys(['monkey', 'zebra', 'donkey', 'cat', 'dog', 'tiger', 'elephant', 'wolf'])
Animal is: monkey
small
Animal is: zebra
big
Animal is: donkey
small
Animal is: cat
small
Animal is: dog
small
Animal is: tiger
big
Animal is: elephant
big
Animal is: wolf
big

#### Q.3. Create a documented python script that will open up the file “Bloom_etal_2018_Reduced_Dataset”. Read through the file and print out the taxon name and their diadromous status. Add up all of the log body sizes and print out the total log body size for all the individuals in the file.

# Pseudocode

#### 1. Import pandas library as pd so as to read our required .csv file
#####import pandas as pd
#### 2. Check to confirm where your .csv file is located 
#####use pwd and ls to check or use the whole path where your .csv is 
#### 3. Read your .csv file and print our the data 
#####data = pd.read_csv('Bloom_etal_2018_Reduced_Dataset.csv')
#### 4. Extract or print out only the rows and colums you need from the whole data 
#####use data.loc[:,['taxa','Reg']] 

where : indicates all rows and ['taxa','Reg'] indicates the columns we need
#### 5. create a list of logbodysize numbers from .csv file 
#####print(List_logbodysize = data.logbodysize.to_list( ))
#### 6. Add all the numbers in the list using for loop
#####total = 0
#####for element in range(0, len(List_logbodysize)):

    total = total + List_logbodysize[element]
    
    print("Sum of all elements in given List_logbodysize: ", total)
#### 7. Make a new column in your .csv file that has the total logbodysize for all the individuals in the file 
#####data ['total_logbodysize'] = 52.079318752000006

data

In [8]:
#import panadas library
import pandas as pd

In [9]:
pwd

'/Users/pankajbhatta/Desktop/PB-HomeworkClub'

In [10]:
#read your .csv file 
data = pd.read_csv ('Bloom_etal_2018_Reduced_Dataset.csv')
data

                           taxa  logbodysize  trophic_position             Reg
0                Alosa_alabamae     1.707570          0.431364      diadromous
1                   Alosa_alosa     1.778151          0.556303      diadromous
2                  Alosa_fallax     1.778151          0.556303      diadromous
3               Alosa_mediocris     1.778151          0.612784      diadromous
4          Alosa_pseudoharengus     1.602060          0.544068      diadromous
5             Alosa_sapidissima     1.790285          0.544068      diadromous
6      Amazonsprattus_scintilla     0.301030          0.531479  non-diadromous
7              Anchoa_chamensis     0.778151          0.518514  non-diadromous
8                 Anchoa_cubana     0.845098          0.518514  non-diadromous
9          Anchoa_delicatissima     0.903090          0.518514  non-diadromous
10          Anchoa_lamprotaenia     0.963788          0.531479  non-diadromous
11              Anchoa_lyolepis     0.845098          0.531479  non-diadromous
12                 Anchoa_parva     0.778151          0.518514  non-diadromous
13            Anchoa_schofieldi     0.792392          0.518514  non-diadromous
14        Anchovia_surinamensis     1.093422          0.477121  non-diadromous
15          Anchoviella_balboae     0.857332          0.505150  non-diadromous
16     Anchoviella_brevirostris     0.857332          0.505150  non-diadromous
17           Anchoviella_jamesi     0.698970          0.491362  non-diadromous
18   Anchoviella_lepidentostole     1.064458          0.491362      diadromous
19       Anchoviella_manamensis     0.397940          0.491362  non-diadromous
20       Anodontostoma_chacunda     1.342423          0.447158      diadromous
21       Cetengraulis_edentulus     1.113943          0.322219  non-diadromous
22  Chirocentrodon_bleekerianus     0.954243          0.518514  non-diadromous
23      Clupeichthys_perakensis     0.602060          0.477121  non-diadromous
24        Clupeoides_borneensis     0.903090          0.491362  non-diadromous
25                 Coilia_nasus     1.544068          0.477121      diadromous
26          Ehirava_fluviatilis     0.698970          0.491362  non-diadromous
27        Encrasicholina_devisi     0.903090          0.518514  non-diadromous
28          Engraulis_eurystole     1.190332          0.462398  non-diadromous
29          Escualosa_thoracata     1.000000          0.505150  non-diadromous
30          Ethmalosa_fimbriata     1.544068          0.397940      diadromous
31      Gilchristella_aestuaria     1.000000          0.491362  non-diadromous
32                  Hilsa_kelee     1.387390          0.462398      diadromous
33         Hyperlophus_vittatus     1.000000          0.531479  non-diadromous
34       Jenkinsia_lamprotaenia     0.838849          0.518514  non-diadromous
35         Microthrissa_congica     0.778151          0.491362  non-diadromous
36            Pellona_harroweri     1.113943          0.623249  non-diadromous
37          Pellonula_leonensis     0.929419          0.518514      diadromous
38              Pellonula_vorax     1.079181          0.491362      diadromous
39        Potamalosa_richmondia     1.505150          0.518514      diadromous
40               Ramnogaster_sp     0.903090          0.531479  non-diadromous
41      Rhinosardinia_bahiensis     0.903090          0.531479  non-diadromous
42           Sauvagella_robusta     0.672098          0.491362  non-diadromous
43      Sierrathrissa_leonensis     0.477121          0.491362  non-diadromous
44    Spratelloides_delicatulus     0.845098          0.491362  non-diadromous
45           Stolephorus_waitei     0.973128          0.518514  non-diadromous
46      Stolothrissa_tanganicae     1.000000          0.431364  non-diadromous
47      Sundasalanx_mekongensis     0.447158          0.491362  non-diadromous
48             Tenualosa_ilisha     1.778151          0.462398      diadromous
49        Thryssa_cf_dussumieri     1.041393          0.447158  non-diadromous

In [11]:
#Extacting only the taxon name and their diadromous status
data.loc[:,['taxa','Reg']]

                           taxa             Reg
0                Alosa_alabamae      diadromous
1                   Alosa_alosa      diadromous
2                  Alosa_fallax      diadromous
3               Alosa_mediocris      diadromous
4          Alosa_pseudoharengus      diadromous
5             Alosa_sapidissima      diadromous
6      Amazonsprattus_scintilla  non-diadromous
7              Anchoa_chamensis  non-diadromous
8                 Anchoa_cubana  non-diadromous
9          Anchoa_delicatissima  non-diadromous
10          Anchoa_lamprotaenia  non-diadromous
11              Anchoa_lyolepis  non-diadromous
12                 Anchoa_parva  non-diadromous
13            Anchoa_schofieldi  non-diadromous
14        Anchovia_surinamensis  non-diadromous
15          Anchoviella_balboae  non-diadromous
16     Anchoviella_brevirostris  non-diadromous
17           Anchoviella_jamesi  non-diadromous
18   Anchoviella_lepidentostole      diadromous
19       Anchoviella_manamensis  non-diadromous
20       Anodontostoma_chacunda      diadromous
21       Cetengraulis_edentulus  non-diadromous
22  Chirocentrodon_bleekerianus  non-diadromous
23      Clupeichthys_perakensis  non-diadromous
24        Clupeoides_borneensis  non-diadromous
25                 Coilia_nasus      diadromous
26          Ehirava_fluviatilis  non-diadromous
27        Encrasicholina_devisi  non-diadromous
28          Engraulis_eurystole  non-diadromous
29          Escualosa_thoracata  non-diadromous
30          Ethmalosa_fimbriata      diadromous
31      Gilchristella_aestuaria  non-diadromous
32                  Hilsa_kelee      diadromous
33         Hyperlophus_vittatus  non-diadromous
34       Jenkinsia_lamprotaenia  non-diadromous
35         Microthrissa_congica  non-diadromous
36            Pellona_harroweri  non-diadromous
37          Pellonula_leonensis      diadromous
38              Pellonula_vorax      diadromous
39        Potamalosa_richmondia      diadromous
40               Ramnogaster_sp  non-diadromous
41      Rhinosardinia_bahiensis  non-diadromous
42           Sauvagella_robusta  non-diadromous
43      Sierrathrissa_leonensis  non-diadromous
44    Spratelloides_delicatulus  non-diadromous
45           Stolephorus_waitei  non-diadromous
46      Stolothrissa_tanganicae  non-diadromous
47      Sundasalanx_mekongensis  non-diadromous
48             Tenualosa_ilisha      diadromous
49        Thryssa_cf_dussumieri  non-diadromous

In [12]:
#creating a list of logbodysize from .csv file
List_logbodysize = data.logbodysize.to_list()
print(List_logbodysize)

[1.707570176, 1.77815125, 1.77815125, 1.77815125, 1.602059991, 1.790285164, 0.301029996, 0.77815125, 0.84509804, 0.903089987, 0.963787827, 0.84509804, 0.77815125, 0.792391689, 1.093421685, 0.857332496, 0.857332496, 0.698970004, 1.064457989, 0.397940009, 1.342422681, 1.113943352, 0.954242509, 0.602059991, 0.903089987, 1.544068044, 0.698970004, 0.903089987, 1.190331698, 1.0, 1.544068044, 1.0, 1.387389826, 1.0, 0.838849091, 0.77815125, 1.113943352, 0.929418926, 1.079181246, 1.505149978, 0.903089987, 0.903089987, 0.672097858, 0.477121255, 0.84509804, 0.973127854, 1.0, 0.447158031, 1.77815125, 1.041392685]

In [13]:
total = 0
 
# Iterate each element in List_logbodysize
# and add them in variable total
for element in range(0, len(List_logbodysize)):
    total = total + List_logbodysize[element]
    
print("Sum of all elements in given List_logbodysize: ", total)

Sum of all elements in given List_logbodysize:  52.079318752000006

In [14]:
#adding a column named total_logbodysize in our data file 
data ['total_logbodysize'] = 52.079318752000006
data

,taxa,logbodysize,trophic_position,Reg,total_logbodysize
0,Alosa_alabamae,1.707570,0.431364,diadromous,52.079319
1,Alosa_alosa,1.778151,0.556303,diadromous,52.079319
2,Alosa_fallax,1.778151,0.556303,diadromous,52.079319
3,Alosa_mediocris,1.778151,0.612784,diadromous,52.079319
4,Alosa_pseudoharengus,1.602060,0.544068,diadromous,52.079319
5,Alosa_sapidissima,1.790285,0.544068,diadromous,52.079319
6,Amazonsprattus_scintilla,0.301030,0.531479,non-diadromous,52.079319
7,Anchoa_chamensis,0.778151,0.518514,non-diadromous,52.079319
8,Anchoa_cubana,0.845098,0.518514,non-diadromous,52.079319
9,Anchoa_delicatissima,0.903090,0.518514,non-diadromous,52.079319
10,Anchoa_lamprotaenia,0.963788,0.531479,non-diadromous,52.079319
11,Anchoa_lyolepis,0.845098,0.531479,non-diadromous,52.079319
12,Anchoa_parva,0.778151,0.518514,non-diadromous,52.079319
13,Anchoa_schofieldi,0.792392,0.518514,non-diadromous,52.079319
14,Anchovia_surinamensis,1.093422,0.477121,non-diadromous,52.079319
15,Anchoviella_balboae,0.857332,0.505150,non-diadromous,52.079319
16,Anchoviella_brevirostris,0.857332,0.505150,non-diadromous,52.079319
17,Anchoviella_jamesi,0.698970,0.491362,non-diadromous,52.079319
18,Anchoviella_lepidentostole,1.064458,0.491362,diadromous,52.079319
19,Anchoviella_manamensis,0.397940,0.491362,non-diadromous,52.079319
20,Anodontostoma_chacunda,1.342423,0.447158,diadromous,52.079319
21,Cetengraulis_edentulus,1.113943,0.322219,non-diadromous,52.079319
22,Chirocentrodon_bleekerianus,0.954243,0.518514,non-diadromous,52.079319
23,Clupeichthys_perakensis,0.602060,0.477121,non-diadromous,52.079319
24,Clupeoides_borneensis,0.903090,0.491362,non-diadromous,52.079319
25,Coilia_nasus,1.544068,0.477121,diadromous,52.079319
26,Ehirava_fluviatilis,0.698970,0.491362,non-diadromous,52.079319
27,Encrasicholina_devisi,0.903090,0.518514,non-diadromous,52.079319
28,Engraulis_eurystole,1.190332,0.462398,non-diadromous,52.079319
29,Escualosa_thoracata,1.000000,0.505150,non-diadromous,52.079319
30,Ethmalosa_fimbriata,1.544068,0.397940,diadromous,52.079319
31,Gilchristella_aestuaria,1.000000,0.491362,non-diadromous,52.079319
32,Hilsa_kelee,1.387390,0.462398,diadromous,52.079319
33,Hyperlophus_vittatus,1.000000,0.531479,non-diadromous,52.079319
34,Jenkinsia_lamprotaenia,0.838849,0.518514,non-diadromous,52.079319
35,Microthrissa_congica,0.778151,0.491362,non-diadromous,52.079319
36,Pellona_harroweri,1.113943,0.623249,non-diadromous,52.079319
37,Pellonula_leonensis,0.929419,0.518514,diadromous,52.079319
38,Pellonula_vorax,1.079181,0.491362,diadromous,52.079319
39,Potamalosa_richmondia,1.505150,0.518514,diadromous,52.079319
40,Ramnogaster_sp,0.903090,0.531479,non-diadromous,52.079319
41,Rhinosardinia_bahiensis,0.903090,0.531479,non-diadromous,52.079319
42,Sauvagella_robusta,0.672098,0.491362,non-diadromous,52.079319
43,Sierrathrissa_leonensis,0.477121,0.491362,non-diadromous,52.079319
44,Spratelloides_delicatulus,0.845098,0.491362,non-diadromous,52.079319
45,Stolephorus_waitei,0.973128,0.518514,non-diadromous,52.079319
46,Stolothrissa_tanganicae,1.000000,0.431364,non-diadromous,52.079319
47,Sundasalanx_mekongensis,0.447158,0.491362,non-diadromous,52.079319
48,Tenualosa_ilisha,1.778151,0.462398,diadromous,52.079319
49,Thryssa_cf_dussumieri,1.041393,0.447158,non-diadromous,52.079319

# Thank you! :)